### ISSUE TITLE
Set, help

### ISSUE THREAD

**Issue by viviskas** [gitextensions/gitextensions.github.io#12]
How to enable in player AIMP?
- ["<preset id="23" name="Flat 20k (20-Band Graphic)" bind="0" lock="0" preamp="0.000000" bound_devices="1887942956543514094,6694220931520792069">
<band type="PEAKEQ" gain="0" freq="27.62133" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="39.0625" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="55.24271" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="78.125" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="110.4851" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="156.25" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="220.9707" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="312.5" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="441.9417" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="625" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="883.8834" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="1250" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="1767.765" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="2500" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="3535.531" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="5000" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="7071.064" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="10000" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="14142.12" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="20000" BW="0.5"/>
</preset>"
 content://0@media/external/file/90561#:~:text=preset%20id%3D%2223,%3C/preset%3E ]

**Comment by viviskas** [comment]
- ["<preset id="23" name="Flat 20k (20-Band Graphic)" bind="0" lock="0" preamp="0.000000" bound_devices="1887942956543514094,6694220931520792069">
<band type="PEAKEQ" gain="0" freq="27.62133" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="39.0625" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="55.24271" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="78.125" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="110.4851" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="156.25" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="220.9707" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="312.5" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="441.9417" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="625" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="883.8834" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="1250" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="1767.765" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="2500" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="3535.531" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="5000" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="7071.064" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="10000" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="14142.12" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="20000" BW="0.5"/>
</preset>"
 content://0@media/external/file/90561#:~:text=preset%20> - # id%3D%2223,%3C/preset%3E] _"<preset id="23" name="Flat 20k (20-Band Graphic)" bind="0" lock="0" preamp="0.000000" bound_devices="1887942956543514094,6694220931520792069">
<band type="PEAKEQ" gain="0" freq="27.62133" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="39.0625" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="55.24271" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="78.125" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="110.4851" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="156.25" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="220.9707" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="312.5" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="441.9417" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="625" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="883.8834" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="1250" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="1767.765" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="2500" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="3535.531" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="5000" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="7071.064" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="10000" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="14142.12" BW="0.5"/>
<band type="PEAKEQ" gain="0" freq="20000" BW="0.5"/>
</preset>"
 content://0@media/external/file/90561#:~:text=preset%20id%3D%2223,%3C/preset%3E_

**Comment by viviskas** [comment]
> - ["<preset id="23" name="Flat 20k (20-Band Graphic)" bind="0" lock="0" preamp="0.000000" bound_devices="1887942956543514094,6694220931520792069">
> <band type="PEAKEQ" gain="0" freq="27.62133" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="39.0625" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="55.24271" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="78.125" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="110.4851" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="156.25" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="220.9707" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="312.5" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="441.9417" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="625" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="883.8834" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="1250" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="1767.765" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="2500" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="3535.531" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="5000" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="7071.064" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="10000" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="14142.12" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="20000" BW="0.5"/>
> </preset>"
>  content://0@media/external/file/90561#:~:text=preset%20> - # id%3D%2223,%3C/preset%3E] _"<preset id="23" name="Flat 20k (20-Band Graphic)" bind="0" lock="0" preamp="0.000000" bound_devices="1887942956543514094,6694220931520792069">
> <band type="PEAKEQ" gain="0" freq="27.62133" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="39.0625" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="55.24271" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="78.125" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="110.4851" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="156.25" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="220.9707" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="312.5" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="441.9417" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="625" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="883.8834" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="1250" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="1767.765" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="2500" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="3535.531" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="5000" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="7071.064" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="10000" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="14142.12" BW="0.5"/>
> <band type="PEAKEQ" gain="0" freq="20000" BW="0.5"/>
> </preset>"
>  content://0@media/external/file/90561#:~:text=preset%20id%3D%2223,%3C/preset%3E_

**Comment by viviskas** [comment]
How to enable?

**Comment by viviskas** [comment]
?

**Comment by pmiossec** [comment]
@viviskas please stop posting here. You post in the wrong place.
