### ISSUE TITLE
gitextensions.github.io does not redirect from HTTP to HTTPS

### ISSUE THREAD

**Issue by osiris-plus** [gitextensions/gitextensions.github.io#15]
When you google for git extensions, non-HTTPS link is returned in the results.

![image](https://github.com/gitextensions/gitextensions.github.io/assets/65327967/7802c201-2274-4057-bc2f-60c67f4733f6)

I suggest enabling http -> https redirect and HSTS if possible.

**Comment by gerhardol** [comment]
I updated the GitHub pages according to https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https
Changed some http: settings in #16
