### ISSUE TITLE
Index page subheading appears to be factually incorrect

### ISSUE THREAD

**Issue by david-in-perth** [gitextensions/gitextensions.github.io#2]
The index page says:

> Git Extensions is the only graphical user interface for Git that allows you control Git without using the commandline

This is not true: [TortoiseGit](https://tortoisegit.org/) and Atlassian Sourcetree ([link 1](https://www.sourcetreeapp.com/), [link 2](https://www.atlassian.com/software/sourcetree)) are two other graphical user interface that allows users to control Git without using the command line. GitHub for Windows probably counts as well, though it doesn't allow anything near the full Git feature set/workflow.

If there are justifications that the statement is true, perhaps because certain features are not accessible from the GUI of these other tools, then the website needs to list those justifications (e.g. on a sub-page, linked to at the end of the statement).

Otherwise, the statement should be rewritten to something else that is either factually correct, or is a matter of opinion.
For example, replace "the only" with "a":

> Git Extensions is a graphical user interface for Git that allows you control Git without using the command line

**Comment by jbialobr** [comment]
Thank you. I believe the statement was true, when it was created a long time ago.
